# Base configuration shared across all environments
# Override in environment-specific config.yaml files

cloud_provider: aws

deployment:
  infrastructure_source: auto
  strategy: rolling
  timeout_minutes: 60

features:
  enable_monitoring: true
  enable_backup: false
  enable_encryption: true

quality_gates:
  code_coverage_threshold: 80
  security_scan: true
