# Example Configuration for Multi-Environment Setup
# This shows how different environments can override base configuration

# Development Environment (config/environments/dev.yaml)
development:
  cloud_provider: aws
  environment: dev
  region: us-west-2
  deployment:
    auto_approve: true  # Auto-approve in dev
    timeout_minutes: 30
  features:
    enable_monitoring: false  # Save costs in dev
    enable_backup: false
    enable_multi_az: false
  resources:
    compute:
      lambda_memory_mb: 256  # Smaller resources for dev
      glue_max_capacity: 1
  notifications:
    slack:
      channel: "#f1-dev"
      on_start: true  # More verbose in dev

# Staging Environment (config/environments/staging.yaml)
staging:
  cloud_provider: aws
  environment: staging
  region: us-west-2
  deployment:
    strategy: blue-green
    auto_approve: false
    timeout_minutes: 45
  features:
    enable_monitoring: true
    enable_backup: true
    enable_multi_az: false
  testing:
    performance_tests: true  # Full performance testing in staging
    security_tests: true
  resources:
    compute:
      lambda_memory_mb: 512
      glue_max_capacity: 2
  notifications:
    slack:
      channel: "#f1-staging"

# Production Environment (config/environments/prod.yaml)
production:
  cloud_provider: aws
  environment: prod
  region: us-east-1
  deployment:
    strategy: blue-green
    auto_approve: false
    timeout_minutes: 120
  features:
    enable_monitoring: true
    enable_backup: true
    enable_encryption: true
    enable_multi_az: true
    enable_cost_alerts: true
  quality_gates:
    code_coverage_threshold: 90  # Higher threshold for prod
    security_scan_threshold: low  # Stricter security for prod
  resources:
    compute:
      lambda_memory_mb: 1024  # More resources for prod
      lambda_timeout_seconds: 900
      glue_max_capacity: 10
    storage:
      data_retention_days: 2555  # 7 years for prod
      backup_retention_days: 90
  notifications:
    slack:
      channel: "#f1-prod"
    email:
      enabled: true
      recipients: ["devops@company.com", "data-team@company.com"]
    pagerduty:
      enabled: true
      service_key: "your-pagerduty-service-key"
  pipeline:
    approval_required_for_prod: true
    rollback_on_failure: true

# Multi-Cloud Example (different cloud providers per environment)
multi_cloud_example:
  dev:
    cloud_provider: aws
    region: us-west-2
  staging:
    cloud_provider: azure
    region: eastus
  prod:
    cloud_provider: gcp
    region: us-central1-a